name: deploy-docs

on: [push]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2

      - name: Deploy Github Pages
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: ins-x/vt
          TARGET_BRANCH: master
          BUILD_SCRIPT: pnpm install && pnpm run build:docs
          BUILD_DIR: packages/docs/docs/.vuepress/dist
